name: runme install
description: Install runme

inputs:
  go-version:
    type: string
    default: '1.24'
    required: true
  version:
    type: string
    default: v3.12.2
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}

    - name: Install runme
      shell: bash
      run: go install github.com/stateful/runme/v3@${{ inputs.version }}
