name: runme install
description: Install runme

inputs:
  go-version:
    type: string
    default: '1.24'
    required: true
  version:
    type: string
    default: v3.12.4
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup folder
      run: |
        mkdir -p $HOME/.local/bin

    - name: Cache runme
      uses: actions/cache@v4
      with:
        path: ~/.local/bin
        key: runme-3.12.4-linux-x86_64

    - name: Setup runme
      run: |
        if [ ! -f "$HOME/.local/bin/runme" ]; then
          curl -fsSL "https://download.stateful.com/runme/3.12.4/runme_linux_x86_64.tar.gz" | tar -xz -C "$HOME/.local/bin"
          chmod +x "$HOME/.local/bin/runme"
        fi
        echo "$HOME/.local/bin" >> $GITHUB_PATH
