name: ahab launch
description: ahab launch

inputs:
  cli-args:
    type: string
    default: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Debug
      shell: bash
      run: |
        ls -la $GITHUB_WORKSPACE/
        ls -la $RUNNER_WORKSPACE/github-actions/

    - name: Debug
      shell: bash
      run: |
        printenv

    - name: Setup
      shell: bash
      run: |
        mkdir -p $HOME/.local/bin
        echo "$HOME/.local/bin" >> $GITHUB_PATH
        cp ahab $HOME/.local/bin/ahab

    - name: Debug 2
      shell: bash
      run: |
        ls -la $HOME/.local/bin

    - name: Run ahab
      shell: bash
      run: ahab --version
