name: ahab launch
description: ahab launch

inputs:
  cli-args:
    type: string
    default: ''
    required: true

runs:
  using: "composite"
  steps:
    - name: Login
      env:
        AHAB_TOKEN: ${{ secrets.AHAB_TOKEN }}
      shell: bash
      run: |
        echo "$AHAB_TOKEN" | gh auth login --with-token

    - name: Download release
      shell: bash
      run: |
        gh release download v0.0.4 -R vrunoa/ahab --pattern 'ahab_0.0.4_linux_386.tar.gz'

    - name: Debug
      shell: bash
      run: |
        ls -la ./

