name: android
inputs:
  node-version:
    type: string
    default: 16.x
    required: true

runs:
  using: "composite"
  steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2

    - name: Setup node
      uses: vrunoa/github-actions/node@main

    - name: Install dependencies
      shell: bash
      run: |
        npm ci

    - name: Install system-image
      shell: bash
      run: |
        sdkmanager "system-images;android-31;google_apis;x86_64"

    - name: Install emulator
      shell: bash
      run: |
        sdkmanager "emulator"

    - name: Create emulator
      shell: bash
      run: |
        avdmanager create avd --name appium-avd --package "system-images;android-31;google_apis;x86_64" --tag "google_apis" --abi "x86_64" --device "pixel_3a"

    - name: Set emulator PATH
      shell: bash
      run: echo "${ANDROID_SDK_ROOT}/emulator" >> $GITHUB_PATH

    - name: Start emulator
      shell: bash
      run: ./src/index.js
