on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  AHAB_TOKEN: ${{ secrets.AHAB_TOKEN }}

jobs:

  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: vrunoa/github-actions/ahab@feat/add-ahab
        with:
          ahab-token: ${{ env.AHAB_TOKEN }}
          cli-args: --version

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup runme
      uses: vrunoa/github-actions/runme@main
      with:
        go-version: 1.24

    - name: Setup node
      uses: vrunoa/github-actions/node@main

  android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup android
        uses: vrunoa/github-actions/android@android-setup
