on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Setup Android SDK
      uses: vrunoa/github-actions/android-sdk@android-setup

    - name: Setup runme
      uses: vrunoa/github-actions/runme@main

    - name: Setup node
      uses: vrunoa/github-actions/node@main
