on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup runme
      uses: vrunoa/github-actions/runme@feat/update

    - name: Setup node
      uses: vrunoa/github-actions/node@main

  android:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup android
        uses: vrunoa/github-actions/android@android-setup
